# Setup
title: Zápisky VŠE.FIS.AI
url: http://matej.tech
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:

# Custom vars
version: 3.0.0

# Navbar page list
nav:

  # - title: Zápisky
  #   url: _notes/test.html

  # - title: Materiály
  #   url: _materials/test.md

  # - title: O mně
  #   url: /about
  
  - title: Zápisky
    url: https://matejtechlovsky.github.io/ai/notes/predmety 
  
  - title: Materiály
    url: https://matejtechlovsky.github.io/ai/materials/predmety
